config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'mainpage#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :orders do
    resources :line_products
  end

  resources :categories, only: [:show]

  resources :products do
     resources :messages
     end

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # user||=User.new


    if user.nil?
      can :read, Product
      can :read, Message
    else
      can :manage, Order, :user_id => user.id
      can :create, Message
      can :read, Product



    end

  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/line_product.rb
class LineProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product, counter_cache: true


end

app/models/message.rb
class Message < ApplicationRecord
  extend Enumerize

  belongs_to :user
  belongs_to :product
  enumerize :status, in: [:appruved, :unapproved], default: :unapproved
  validates :text, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_products
  has_many :products, through: :line_products
  belongs_to :user

  def total_price

    @total_price||= line_products.to_a.sum { |item| item.product.price }
    end
  end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :messages
  belongs_to :category
  has_many :order_comments, -> { order('created_at desc') } , class_name: Message
  has_many :line_products
  has_many :orders, through: :line_products
  ratyrate_rateable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :title, :body, :avatar, presence: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { :greater_than_or_equal_to => 0.0 }

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :messages
  has_many :orders
  ratyrate_rater


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders=Order.all
  end
  def new
    @order = Order.new
  end
  def show
    @order=Order.find(params[:id])
    @line_products=@order.line_products.all
    render :show
  end
  def create
    @order=current_user.orders.create(order_params)
    @order.sum=@order.total_price

    @order.save

    if request.xhr?
      render json: { success: true }
    else
      redirect_to product_path(@product)
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:sum)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  # GET /products
  # GET /products.json
  load_and_authorize_resource
  def index
    @q=Product.ransack(params[:q])
    @products = @q.result.paginate(:page=> params[:page], :per_page => 5 ).order('created_at DESC')
    # @q.build_condition
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product=Product.find(params[:id])
    @messages=Message.where(product_id: @product).paginate(:page=> params[:page], :per_page => 5 ).order('created_at DESC')
    #@Messages=@product.order_comments
    render :show
  end

  # GET /products/new
  def new
    @product = Product.new

  end

  # GET /products/1/edit
  def edit
    @product=Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :body, :price, :avatar, :category_id)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_products_helper.rb
module LineProductsHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def link_to_product(product)
    link_to product.title, product_path(product)
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
    <div class="field">
      <%= f.label :category_id%>
      <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %>
    </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

    <div class="field">
      <%= f.label  :avatar  %><br />
      <%= f.file_field :avatar%>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% unless user_signed_in? %>
    <%= link_to 'Sign in', new_user_session_path%>
<%end%>
  <div class="container">

  <%= search_form_for @q do |f| %>
    <div class="field">
    <%= f.label :title_or_body_cont %>
    <%= f.search_field :title_or_body_cont, placeholder: "Text for search"  %>
    </div>
    <div class="field">
      <%= f.label :price_gteq, "Price between" %>
      <%= f.text_field :price_gteq, placeholder: "Minumum Price" %>
      <%= f.label :price_lteq, "and" %>
      <%= f.text_field :price_lteq, placeholder: "Maximum Price" %>
    </div>
    <%= f.select :category_id_eq, options_from_collection_for_select(Category.all, 'id', 'name'), include_blank: true %>
    <span class=" glyphicon glyphicon-filter">
      <%= f.submit %>
    </span>
  <%end %>
    <%= button_to "Clear", products_path, method: 'get' %>
    <%= sort_link(@q, :title, "Product Name") %>
    <%= sort_link(@q, :price, "Price") %>
  </div>
<div class="container">
  <div class="row list-group">

    <% @products.each do |product| %>
       <div class="item  col-xs-2 col-lg-2">
        <div class="thumbnail">
        <%=image_tag product.avatar.url(:medium) %>
          <div class="caption">
        <h4><%= link_to_product product%></h4>
        <h4><%= product.price %></h4>
          </div>
        </div>
       </div>

    <% end %>
  </div>
  <%= will_paginate @products %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% unless user_signed_in? %>
    <%= link_to 'Войти', new_user_session_path%>
<%end%><p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
   <%= image_tag @product.avatar %>
</p>
<p>
  <strong>Body:</strong>
  <%= @product.body %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<%= rating_for @product %>
<div>
     <%= link_to 'Back', products_path %>
</div>

<% if can? :create, Message %>
<p>
     <%= form_for([@product, @product.messages.build]) do |f| %>
      <%= f.text_field :text, placeholder: 'Add your message..' %>
      <%= f.submit class: 'btn btn-primary' %>
        <div id="flash">
      <%=  flash[:notice]  %>
        </div>
    <% end %>
  <% end %>
</p>

<table id='messages' class='table'>
  <thead>
  <th>
    Name
  </th>
  <th>
    Comment
  </th>
  <th>
    Date
  </th>

  </thead>
  <tbody>
  <% @messages.each do |message| %>
      <% next unless message.persisted? %>
      <% unless message.status == "unapproved"%>
      <td><%= message.user.email%></td>
        <td><%= message.text %></td>
        <% end %>
  </tbody>
  <% end %>

</table>
<%= will_paginate @messages %>